name: Bienvenida!

on:
  push:
    branches:
      - main

jobs:
  saludo_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Saludar
        run: |
          echo "Hola Github Actions!!!"
      - name: Date
        run: |
          echo $NOW
      - name: ls -l command
        run: |
          ls -l