name: Bienvenida!

on:
  push:
    branches:
      - main

jobs:
  saludo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: |
          echo "Hola Github Actions!!!"
      - name: Date
        run: |
          echo ${{ github.event.head_commit.timestamp }}
      - name: ls -l command
        run: |
          ls -l